# Site settings
author: Ryan McCahon
title: The Next Step
header-img: img/home-bg.png
email: mccahonr@yahoo.com
copyright_name: Ryan McCahon
description: > # this means to ignore newlines until "baseurl:"
  My journey through coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mccahonr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
